#Test code generated by MISTA



class SDN_Firewall5Tester_RT( unittest.TestCase):

	
	
	def setUp() :
		sdn_firewall5 = new SDN_Firewall5()
	
	
	def test1() :
		print "Test case 1"
	

	if __name__ == '__main__':
		suite = unittest.TestSuite()
		suite.addTest(unittest.makeSuite(SDN_Firewall5Tester_RT))
		unittest.TextTestRunner(verbosity=2).run(suite)