/*Test code generated by ISTA*/

#include <controller.h>


void setUp(){
}

void assert(int condition, char *errorMessage) {
	if (!condition){
		printf("%s\n\n", errorMessage);
		system("PAUSE");
		exit(0);
	}
}

void test1() {
	printf("Test case 1\n");
	setUp();
	engineOn
	assert(getState() == ACTIVE, "1_1");
	engineOff
	assert(getState() == INACTIVE, "1_1_1");
}

void test2() {
	printf("Test case 2\n");
	setUp();
	engineOn
	accelerator
	assert(getState() == ACTIVE, "1_1_2");
}

void test3() {
	printf("Test case 3\n");
	setUp();
	engineOn
	brake
	assert(getState() == ACTIVE, "1_1_3");
}

void test4() {
	printf("Test case 4\n");
	setUp();
	engineOn
	on
	assert(getState() == CRUISING, "1_1_4");
	engineOff
	assert(getState() == INACTIVE, "1_1_4_1");
}

void test5() {
	printf("Test case 5\n");
	setUp();
	engineOn
	on
	accelerator
	assert(getState() == STANDBY, "1_1_4_2");
	engineOff
	assert(getState() == INACTIVE, "1_1_4_2_1");
}

void test6() {
	printf("Test case 6\n");
	setUp();
	engineOn
	on
	accelerator
	on
	assert(getState() == CRUISING, "1_1_4_2_2");
}

void test7() {
	printf("Test case 7\n");
	setUp();
	engineOn
	on
	accelerator
	resume
	assert(getState() == CRUISING, "1_1_4_2_3");
}

void test8() {
	printf("Test case 8\n");
	setUp();
	engineOn
	on
	brake
	assert(getState() == STANDBY, "1_1_4_3");
}

void test9() {
	printf("Test case 9\n");
	setUp();
	engineOn
	on
	off
	assert(getState() == STANDBY, "1_1_4_4");
}

void testAll(){
	
	test1();
	test2();
	test3();
	test4();
	test5();
	test6();
	test7();
	test8();
	test9();
	
}

int main(void){
	testAll();
	printf("\n\n");
	system("PAUSE");
	return 0;
}
