//Test code generated by MISTA

package test;

import simulation.CarSimulator;
import org.junit.*;
import static org.junit.Assert.*;


public class CarSimulatorTester_RT {

	private CarSimulator carsimulator;
	
	@Before
	public void setUp()  throws Exception {
		carsimulator = new CarSimulator();
	}
	
	@Test
	public void test1() throws Exception {
		System.out.println("Test case 1");
		carsimulator.engineOn();
		assertTrue("1_1", getIgnition());
		assertTrue("1_1", getThrottle()==0);
		assertTrue("1_1", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("1_1_1", !getIgnition());
	}

	@Test
	public void test2() throws Exception {
		System.out.println("Test case 2");
		carsimulator.engineOn();
		carsimulator.accelerator();
		assertTrue("1_1_2", getIgnition());
		assertTrue("1_1_2", getThrottle()>0);
		assertTrue("1_1_2", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("1_1_2_1", !getIgnition());
	}

	@Test
	public void test3() throws Exception {
		System.out.println("Test case 3");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("1_1_2_2", getIgnition());
		assertTrue("1_1_2_2", getThrottle()>0);
		assertTrue("1_1_2_2", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("1_1_2_2_1", !getIgnition());
	}

	@Test
	public void test4() throws Exception {
		System.out.println("Test case 4");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("1_1_2_2_2", getIgnition());
		assertTrue("1_1_2_2_2", getThrottle()>0);
		assertTrue("1_1_2_2_2", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("1_1_2_2_2_1", !getIgnition());
	}

	@Test
	public void test5() throws Exception {
		System.out.println("Test case 5");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("1_1_2_2_2_2", getIgnition());
		assertTrue("1_1_2_2_2_2", getThrottle()>0);
		assertTrue("1_1_2_2_2_2", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test6() throws Exception {
		System.out.println("Test case 6");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test7() throws Exception {
		System.out.println("Test case 7");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test8() throws Exception {
		System.out.println("Test case 8");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test9() throws Exception {
		System.out.println("Test case 9");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test10() throws Exception {
		System.out.println("Test case 10");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test11() throws Exception {
		System.out.println("Test case 11");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test12() throws Exception {
		System.out.println("Test case 12");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test13() throws Exception {
		System.out.println("Test case 13");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test14() throws Exception {
		System.out.println("Test case 14");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test15() throws Exception {
		System.out.println("Test case 15");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test16() throws Exception {
		System.out.println("Test case 16");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test17() throws Exception {
		System.out.println("Test case 17");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test18() throws Exception {
		System.out.println("Test case 18");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test19() throws Exception {
		System.out.println("Test case 19");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test20() throws Exception {
		System.out.println("Test case 20");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test21() throws Exception {
		System.out.println("Test case 21");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test22() throws Exception {
		System.out.println("Test case 22");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test23() throws Exception {
		System.out.println("Test case 23");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test24() throws Exception {
		System.out.println("Test case 24");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test25() throws Exception {
		System.out.println("Test case 25");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test26() throws Exception {
		System.out.println("Test case 26");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test27() throws Exception {
		System.out.println("Test case 27");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test28() throws Exception {
		System.out.println("Test case 28");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test29() throws Exception {
		System.out.println("Test case 29");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test30() throws Exception {
		System.out.println("Test case 30");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test31() throws Exception {
		System.out.println("Test case 31");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test32() throws Exception {
		System.out.println("Test case 32");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test33() throws Exception {
		System.out.println("Test case 33");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test34() throws Exception {
		System.out.println("Test case 34");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test35() throws Exception {
		System.out.println("Test case 35");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test36() throws Exception {
		System.out.println("Test case 36");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test37() throws Exception {
		System.out.println("Test case 37");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test38() throws Exception {
		System.out.println("Test case 38");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test39() throws Exception {
		System.out.println("Test case 39");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test40() throws Exception {
		System.out.println("Test case 40");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test41() throws Exception {
		System.out.println("Test case 41");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test42() throws Exception {
		System.out.println("Test case 42");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test43() throws Exception {
		System.out.println("Test case 43");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test44() throws Exception {
		System.out.println("Test case 44");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test45() throws Exception {
		System.out.println("Test case 45");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test46() throws Exception {
		System.out.println("Test case 46");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test47() throws Exception {
		System.out.println("Test case 47");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test48() throws Exception {
		System.out.println("Test case 48");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test49() throws Exception {
		System.out.println("Test case 49");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test50() throws Exception {
		System.out.println("Test case 50");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test51() throws Exception {
		System.out.println("Test case 51");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test52() throws Exception {
		System.out.println("Test case 52");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test53() throws Exception {
		System.out.println("Test case 53");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test54() throws Exception {
		System.out.println("Test case 54");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test55() throws Exception {
		System.out.println("Test case 55");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test56() throws Exception {
		System.out.println("Test case 56");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test57() throws Exception {
		System.out.println("Test case 57");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test58() throws Exception {
		System.out.println("Test case 58");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
	}

	@Test
	public void test59() throws Exception {
		System.out.println("Test case 59");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("1_1_2_2_2_3", getIgnition());
		assertTrue("1_1_2_2_2_3", getThrottle()==0);
		assertTrue("1_1_2_2_2_3", getBrakepadel()>0);
	}

	@Test
	public void test60() throws Exception {
		System.out.println("Test case 60");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("1_1_2_2_3", getIgnition());
		assertTrue("1_1_2_2_3", getThrottle()==0);
		assertTrue("1_1_2_2_3", getBrakepadel()>0);
	}

	@Test
	public void test61() throws Exception {
		System.out.println("Test case 61");
		carsimulator.engineOn();
		carsimulator.accelerator();
		carsimulator.brake();
		assertTrue("1_1_2_3", getIgnition());
		assertTrue("1_1_2_3", getThrottle()==0);
		assertTrue("1_1_2_3", getBrakepadel()>0);
	}

	@Test
	public void test62() throws Exception {
		System.out.println("Test case 62");
		carsimulator.engineOn();
		carsimulator.brake();
		assertTrue("1_1_3", getIgnition());
		assertTrue("1_1_3", getThrottle()==0);
		assertTrue("1_1_3", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("1_1_3_1", !getIgnition());
	}

	@Test
	public void test63() throws Exception {
		System.out.println("Test case 63");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("1_1_3_2", getIgnition());
		assertTrue("1_1_3_2", getThrottle()>0);
		assertTrue("1_1_3_2", getBrakepadel()==0);
	}

	@Test
	public void test64() throws Exception {
		System.out.println("Test case 64");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("1_1_3_3", getIgnition());
		assertTrue("1_1_3_3", getThrottle()==0);
		assertTrue("1_1_3_3", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("1_1_3_3_1", !getIgnition());
	}

	@Test
	public void test65() throws Exception {
		System.out.println("Test case 65");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("1_1_3_3_2", getIgnition());
		assertTrue("1_1_3_3_2", getThrottle()>0);
		assertTrue("1_1_3_3_2", getBrakepadel()==0);
	}

	@Test
	public void test66() throws Exception {
		System.out.println("Test case 66");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("1_1_3_3_3", getIgnition());
		assertTrue("1_1_3_3_3", getThrottle()==0);
		assertTrue("1_1_3_3_3", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("1_1_3_3_3_1", !getIgnition());
	}

	@Test
	public void test67() throws Exception {
		System.out.println("Test case 67");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("1_1_3_3_3_2", getIgnition());
		assertTrue("1_1_3_3_3_2", getThrottle()>0);
		assertTrue("1_1_3_3_3_2", getBrakepadel()==0);
	}

	@Test
	public void test68() throws Exception {
		System.out.println("Test case 68");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("1_1_3_3_3_3", getIgnition());
		assertTrue("1_1_3_3_3_3", getThrottle()==0);
		assertTrue("1_1_3_3_3_3", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test69() throws Exception {
		System.out.println("Test case 69");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test70() throws Exception {
		System.out.println("Test case 70");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test71() throws Exception {
		System.out.println("Test case 71");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test72() throws Exception {
		System.out.println("Test case 72");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test73() throws Exception {
		System.out.println("Test case 73");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test74() throws Exception {
		System.out.println("Test case 74");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test75() throws Exception {
		System.out.println("Test case 75");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test76() throws Exception {
		System.out.println("Test case 76");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test77() throws Exception {
		System.out.println("Test case 77");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test78() throws Exception {
		System.out.println("Test case 78");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test79() throws Exception {
		System.out.println("Test case 79");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test80() throws Exception {
		System.out.println("Test case 80");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test81() throws Exception {
		System.out.println("Test case 81");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test82() throws Exception {
		System.out.println("Test case 82");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test83() throws Exception {
		System.out.println("Test case 83");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test84() throws Exception {
		System.out.println("Test case 84");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test85() throws Exception {
		System.out.println("Test case 85");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test86() throws Exception {
		System.out.println("Test case 86");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test87() throws Exception {
		System.out.println("Test case 87");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test88() throws Exception {
		System.out.println("Test case 88");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test89() throws Exception {
		System.out.println("Test case 89");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test90() throws Exception {
		System.out.println("Test case 90");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test91() throws Exception {
		System.out.println("Test case 91");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test92() throws Exception {
		System.out.println("Test case 92");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test93() throws Exception {
		System.out.println("Test case 93");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test94() throws Exception {
		System.out.println("Test case 94");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test95() throws Exception {
		System.out.println("Test case 95");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test96() throws Exception {
		System.out.println("Test case 96");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test97() throws Exception {
		System.out.println("Test case 97");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test98() throws Exception {
		System.out.println("Test case 98");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test99() throws Exception {
		System.out.println("Test case 99");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test100() throws Exception {
		System.out.println("Test case 100");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test101() throws Exception {
		System.out.println("Test case 101");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test102() throws Exception {
		System.out.println("Test case 102");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test103() throws Exception {
		System.out.println("Test case 103");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test104() throws Exception {
		System.out.println("Test case 104");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test105() throws Exception {
		System.out.println("Test case 105");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test106() throws Exception {
		System.out.println("Test case 106");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test107() throws Exception {
		System.out.println("Test case 107");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test108() throws Exception {
		System.out.println("Test case 108");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test109() throws Exception {
		System.out.println("Test case 109");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test110() throws Exception {
		System.out.println("Test case 110");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test111() throws Exception {
		System.out.println("Test case 111");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test112() throws Exception {
		System.out.println("Test case 112");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test113() throws Exception {
		System.out.println("Test case 113");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test114() throws Exception {
		System.out.println("Test case 114");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test115() throws Exception {
		System.out.println("Test case 115");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test116() throws Exception {
		System.out.println("Test case 116");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test117() throws Exception {
		System.out.println("Test case 117");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test118() throws Exception {
		System.out.println("Test case 118");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test119() throws Exception {
		System.out.println("Test case 119");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

	@Test
	public void test120() throws Exception {
		System.out.println("Test case 120");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()==0);
		assertTrue("", getBrakepadel()>0);
		carsimulator.engineOff();
		assertTrue("", !getIgnition());
	}

	@Test
	public void test121() throws Exception {
		System.out.println("Test case 121");
		carsimulator.engineOn();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.brake();
		carsimulator.accelerator();
		assertTrue("", getIgnition());
		assertTrue("", getThrottle()>0);
		assertTrue("", getBrakepadel()==0);
	}

}
